### ISSUE TITLE
Request: A way to comment really long strings

### ISSUE THREAD

**Issue by mcandre** [json5/json5#165]
I would enjoy a way to somehow insert comments within really long string values in JSON-ish content. My use case is annotating what different steps do within `boot_command` strings in [packer](https://www.packer.io/) configurations. The problem is, a `boot_command` consists of one rather long single string, so I think the current json5 comment system would only allow comments to appear before or after the entire string, but not inside.

If JSON5 supported implicit string literal concatenation, I think this within-string commenting could be fairly easily implemented and flexibly used:

```
{
  "book":
    "Actus primus, Scena prima.\n" // First act, first scene
    "Enter the Duke of Ephesus, with the Merchant of Siracusa, Iaylor, and other attendants.\n\n"
    "  Marchant. Proceed Solinus to procure my fall,\n"
    "And by the doome of death end woes and all"
}
```

What do you think?

**Comment by jordanbtucker** [comment]
Hey, everyone. I'm going to close this issue because it is incompatible with the [official specification](https://json5.github.io/json5-spec/). If you would like to continue this discussion, please open an issue on the [official specification repository](https://github.com/json5/json5-spec). Please see the new [issues template](https://github.com/json5/json5/blob/master/.github/issue_template.md) for more information. Thanks.
