### ISSUE TITLE
undefined support

### ISSUE THREAD

**Issue by nanodesu88** [json5/json5#171]
whats about undefined? null is fine, but null have a problems in typescript.

**Comment by jordanbtucker** [comment]
I'm closing this issue because it is incompatible with the [official specification](https://json5.github.io/json5-spec/). If you would like to continue this discussion, please open an issue on the [official specification repository](https://github.com/json5/json5-spec). Please see the new [issues template](https://github.com/json5/json5/blob/master/.github/issue_template.md) for more information. Thanks.
