### ISSUE TITLE
Where has JSON4 gone / Why JSON5?

### ISSUE THREAD

**Issue by khullah** [json5/json5#175]
So, researching the web, I know the first versions of JSON used eval on the browser. With ES5, Crockford's JSON2 was standardized and incorporated in all browsers. There is a [JSON3](https://bestiejs.github.io/json3/) library, and this is JSON5. So what happened to JSON4 or why is this project named JSON5?

**Comment by jordanbtucker** [comment]
The 5 in JSON5 isn't so much a version number as it is an indication of what features it includes, namely, several features from ECMAScript 5.

**Comment by khullah** [comment]
Ahhhhhh! I see
Thanks

**Comment by shoogle** [comment]
In other words, JSON5 is not related to standard JSON any more than jsonc, CSON or any other unofficial JSON extension/alternative.

It might be a good idea to put words to that effect on your homepage and README, and perhaps rethink the idea of listing JSON's original creator in the credits since he had nothing to do with this project.
