### ISSUE TITLE
Allow leading comma and empty values in arrays

### ISSUE THREAD

**Issue by aseemk** [json5/json5#19]
_Edit: the original title of this case was to <b>disallow</b> these things, considered bugs. That was fixed, but now the conversation below asks to consider re-allowing them._

ES5 allows these:

``` js
[,]     // => [undefined]
[,null] // => [undefined, null]
```

But I don't think that's needed in JSON5. Let's keep it simple and closer to JSON here.

This implementation currently allows these (by design); let's fix.

**Comment by jordanbtucker** [comment]
Hey, everyone. I'm going to close this issue because it is incompatible with the [official specification](https://json5.github.io/json5-spec/). If you would like to continue this discussion, please open an issue on the [official specification repository](https://github.com/json5/json5-spec). Please see the new [issues template](https://github.com/json5/json5/blob/master/.github/issue_template.md) for more information. Thanks.
