### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [json5/json5#235]
If you want I can write a [TypeScript type declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by jordanbtucker** [comment]
Yes, that would be much appreciated. It's something that I've had on my backlog for awhile, and just haven't found the time for it.

**Comment by geopic** [comment]
Cool, I'll start on it now :+1:

**Comment by lonewarrior556** [comment]
Untill this is done, are these accurate? https://www.npmjs.com/package/@types/json5

**Comment by geopic** [comment]
I'll push some new changes tomorrow which you can get the types from @lonewarrior556, check the pull request 👍

**Comment by jordanbtucker** [comment]
@lonewarrior556 Those typings are mostly correct, but some improvements can be made.

- It doesn't include documentation.
- `parse` could have a type parameter for specifying its return type.
- The `reviver` and `replacer` functions should have `this: any` because they are always called in the context of the property's parent.
- The overzealous use of optional parameters leads to ambiguous overloads.
- The optional parameters should also accept `null`.
- It does not support importing `json5/lib/parse` and `json5/lib/stringify`, which may be useful for those who want to keep their bundles down to the smallest possible size.

I'm hoping to get this published soon.

**Comment by jordanbtucker** [comment]
This was implemented in [v2.2.0](https://github.com/json5/json5/releases/tag/v2.2.0).
