### ISSUE TITLE
How to use json5 package to require file ext `.json` not `.json5` ?

### ISSUE THREAD

**Issue by kytosai** [json5/json5#246]
Currently i can only use json5 package to be able to read .json5 . file

How to use json5 package to require file ext `.json` not `.json5` ?

**Comment by jordanbtucker** [comment]
Are you saying that you want to be able to write code like this?

```js
const data = require('./data.json')
// data.json contains JSON5 formatted data
// even though it has a .json extension.
```

**Comment by kytosai** [comment]
> Are you saying that you want to be able to write code like this?
> 
> ```js
> const data = require('./data.json')
> // data.json contains JSON5 formatted data
> // even though it has a .json extension.
> ```

Yes,exactly !

**Comment by jordanbtucker** [comment]
I do not recommend loading `.json` files this way because the [API is deprecated](https://nodejs.org/api/modules.html#modules_require_extensions), and it will cause all `.json` files required after this code to be parsed by JSON5 (even `.json` files required by other packages), which is slower than the native JSON parser.

Despite the warnings above, if you still want this behavior, the following code will accomplish it. Make sure this code runs before any `.json` files are required if you want them parsed as JSON5.

```js
const fs = require('fs')
const JSON5 = require('json5')

require.extensions['.json'] = function (module, filename) {
  const content = fs.readFileSync(filename, 'utf8')
  try {
      module.exports = JSON5.parse(content)
  } catch (err) {
      err.message = filename + ': ' + err.message
      throw err
  }
}
```
