### ISSUE TITLE
Multi-line verbatim

### ISSUE THREAD

**Issue by ImportTaste** [json5/json5#254]
For instances where you need to represent a block of data that you don't want to have to involve any escape characters in, create a multi-line verbatim lexer. My suggestion is to have it begin with `@'`+linebreak and ending with linebreak+`'@`+linebreak, like so:

```
    "verbatimmultilinestring": @'
"How
now?"
Brown
cow!
'@
```

The linebreak proceeding `@'` and preceding `'@` would not be a part of the string. The `'@` line would need to end with a linebreak, meaning if the text block has a line that starts with `'@` but does not end with a linebreak, it will be treated as part of the text block and not the end of the string.

You could also do a `@"` `"@` version that behaves the same way, except it evaluates escape patterns (meaning backslashes would have to be escaped to be represented).

**Comment by ImportTaste** [comment]
Cool thanks.

**Comment by jordanbtucker** [comment]
I closed this issue because it did not follow the instructions in the issue template.

If you are submitting a bug because you are receiving an error or because this
project is incompatible with the [official JSON5
specification][spec], please continue.

If you are submitting a feature request or code improvement that is compatible
with the [official JSON5 specification][spec], please continue.

> An example of this is adding a `quote` option to `stringify()` that allows the
> user to chose which quote character is used.

If you are submitting a feature request or code improvement that is
*incompatible* with the [official JSON5 specification][spec], please open an
issue on the [specification repository](https://github.com/json5/json5-spec)
instead.

> An example of this is adding first class support for `Date` or `RegExp`
> objects to the JSON5 format. This is outside the scope of this project.

[spec]: https://json5.github.io/json5-spec/

Thank you for your cooperation. You may delete this message and the instructions
above.
