### ISSUE TITLE
SyntaxError when require()ing JSON5 file in Jest test

### ISSUE THREAD

**Issue by kerrickstaley** [json5/json5#294]
## Summary
I'm trying to `require()` a JSON5 file in a Jest test file, like this:
```
require('json5/lib/register');
const data = require('./data.json5');
```
When I do this, I get a `SyntaxError`. It seems like it's trying to parse the `.json5` file as if it's a Javascript source file.

[Here is a GitHub repo with code to reproduce this issue.](https://github.com/kerrickstaley/json5-require-bug-report)

## To reproduce
Run:
```
git clone https://github.com/kerrickstaley/json5-require-bug-report.git
cd json5-require-bug-report
npm install
npm test
```

## Expected output
Test passes.

## Actual output
```
    SyntaxError: Unexpected token '}'

      1 | require('json5/lib/register');
    > 2 | const data = require('./data.json5');
        |              ^
```

## Notes
It works if I convert `data.json5` to a JSON file and then do `require('data.json')` inside `data.test.js`. It also works to do `require('json5/lib/register'); const data = require('data.json5');` inside an `app.js` file that I run with `node app.js`. The only broken combination is JSON5 inside a Jest test.

**Comment by jordanbtucker** [comment]
Thanks for the bug report and example repository. The issue appears to lie with Jest's [lack of support](https://github.com/facebook/jest/issues/281) for Node.js's [`require.extensions` API](https://nodejs.org/dist/latest-v19.x/docs/api/modules.html#requireextensions), which is how `json5/lib/register` works.

`require.extensions` has been deprecated since Node.js v0.10.6, and so it's also deprecated in json5 and will be removed in the next version. I recommend using a file system API to read the file as text and parse it instead.

```js
const fs = require('fs')
const JSON5 = require('json5')

const text = fs.readFileSync('./data.json5', 'utf8')
const data = JSON5.parse(text)
```
