### ISSUE TITLE
Date / time support

### ISSUE THREAD

**Issue by shish** [json5/json5#3]
Most of the methods I've seen for encoding dates and times in JSON seem hacky and non-standard; if you're going to update the standard, doing dates in a nice way would be good.

(I'm not sure what that nice way would be)

**Comment by jordanbtucker** [comment]
mofo syn posted on the JSON5 Google Group:

**I wonder if anyone thought about custom data types e.g. ISO8601**

> ```json
> {"data": !ISO8601 "2013-10-07T18:06:03.048Z"}`
> ```
>
> Above is how yaml would approach this. Obviously not JSON compatible.
>
> Below is how MongelDB approches it:
>
> ```json
> {"data":{"$date":"2013-10-07T18:06:03.048Z"}}`
> ```
>
> -------
>
> Would be interesting to see if there is a way to define custom datatypes in a way that is consistent with javascript V5.

I think @shish summed it up nicely:

> storing as strings and then attempting to turn all strings into dates would have false positives; storing as non-strings breaks the purity of the format

Also, YAML's method would violate one of the core values:

> JSON5 remains a **strict subset of JavaScript**.

Probably the best solution would be to allow `new Date()` or `Date.parse()` as values. When JSON5 is serialized as JSON, it would output the date string, but when serialized as JSON5, it would output `new Date()` or `Date.parse()`.

BTW, `new Date()` and `Date.parse()` are equivalent, so it comes down to which ones feels better. I think my vote is for new `Date()` since it's two characters less.

**Comment by jordanbtucker** [comment]
Correction, `new Date()` and `Date.parse()` are not equivalent, since `new Date()` returns a Date object and `Date.parse()` returns a Number. 

`new Date()` may cause some confusion as to what type of parameter is accepted since it has four overloads:

```javascript
new Date()
new Date(value)
new Date(dateString)
new Date(year, month[, day[, hour[, minutes[, seconds[, milliseconds]]]]])
```

I think JSON5 should only accept strings as parameters (for readability) so `new Date(dateString)` would be the only acceptable overload. But we're still left with ambiguity about what date format are acceptable. I think should be [ISO8601][1] allowed exclusively.

```javascript
new Date('2015-10-08T10:29:00.000Z') // acceptable
new Date('October 8, 2015 10:29 AM') // unacceptable
```

Note that `stringify` will output all ISO8601 fields, but all fields do not need to be specified when parsing:

```javascript
// all acceptable
Date.parse('2015')
Date.parse('2015-10')
Date.parse('2015-10-08')
Date.parse('2015-10-08T10:29Z')
Date.parse('2015-10-08T10:29-08:00')
Date.parse('2015-10-08T10:29:30Z')
Date.parse('2015-10-08T10:29:30-08:00')
Date.parse('2015-10-08T10:29:30.123Z')
Date.parse('2015-10-08T10:29:30.123-08:00')
Date.parse('2015-10-08T10:29:30.123456789Z')      // acceptable, but loses resolution
Date.parse('2015-10-08T10:29:30.123456789-08:00') // acceptable, but loses resolution
```

[1]: http://www.w3.org/TR/NOTE-datetime

**Comment by tracker1** [comment]
An iso format date, with at least yyyy-mm-dd should be parsed and turned into a Date object, it's easy enough to detect.. yes, a hydration script could be used, but at this point the ISO serialization has been standard in ES for over half a decade, so deserializing makes sense, the trouble is the offset, though it's probably best to just use `new Date(Date.parse(str))` and leave it at that for detection.

The following regex should match the above serializations.
```
/^\d{4}\-\d\d-\d\d([T ]\d\d(\:\d\d(\:\d\d(\.\d{3-9)?)?)?(Z|[\+\-]\d\d\:?\d\d)?)?$/
```

.length >= 10, .length <= 35, regex matches use `new Date(Date.parse(str))`

The reason to use `Date.parse` over just `new Date(str)` is because Date.parse is more likely to be polyfilled than the Date itself... (I wrote one of the first polyfills for new Date, and it was rather evil).  There are better fills for Date.parse out there, and in wider usage.

**Comment by jordanbtucker** [comment]
I'm in the process of finalizing v1.0.0, so I've taken another look at `Date` support, and I've been testing out an option for `parse` that will automatically find strings that look like dates and parse them as Date objects. Here's what the API looks like.

```js
const result = JSON5.parse("{dateTime: '2017-09-23T23:53:40.303Z'}", {dates: true})
// `result` is equivalent to { dateTime: new Date('2017-09-23T23:53:40.303Z') }
```

- The date string must be in ISO format with all fields present and in the UTC time zone. In other words, it must be in the format `YYYY-MM-DDTHH:mm:ss.sssZ`. This is the same format returned by `Date.prototype.toJSON()`.
- The second argument of `parse` can be a reviver function or a new options object. The options object can have a `reviver` property and a `dates` property. If `dates` is truthy, then each string will be tested to see if it conforms to the format described earlier, and if so, converted to a `Date` object.
- If a `reviver` function is also defined, then it will be called _after_ all date strings have been converted to `Date` objects.

It has not yet been decided whether this feature will make it into v1.0.0. Please let me know what you think.

This is not an extension to the JSON5 document specification. It is only an extension to the API of this library. JSON5 implementations are not required to implement this API.

You can try this out by using `npm install json5@dates`.

**Comment by aseemk** [comment]
I have the same opinion here as https://github.com/json5/json5/issues/91#issuecomment-332359187.

**Comment by jordanbtucker** [comment]
See my reply at https://github.com/json5/json5/issues/91#issuecomment-333287297.

**Comment by jordanbtucker** [comment]
<details>
<summary>
Here's a polyfill
</summary>

```js
function json5DatesPolyfill() {
    const JSON5 = require('json5')

    const origParse = JSON5.parse

    JSON5.parse = function parse(text, reviver) {
        let root = origParse(text)

        if (reviver != null && typeof reviver === 'object') {
            const dates = reviver.dates
            reviver = reviver.reviver

            if (dates) {
                root = internalize({ '': root }, '', dateReviver)
            }
        }

        if (typeof reviver === 'function') {
            return internalize({ '': root }, '', reviver)
        }

        return root
    }

    function dateReviver(name, value) {
        if (
            typeof value === 'string' &&
            /^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d\.\d\d\dZ$/.test(value)
        ) {
            return new Date(value)
        }

        return value
    }

    function internalize(holder, name, reviver) {
        const value = holder[name]
        if (value != null && typeof value === 'object') {
            for (const key in value) {
                const replacement = internalize(value, key, reviver)
                if (replacement === undefined) {
                    delete value[key]
                } else {
                    value[key] = replacement
                }
            }
        }

        return reviver.call(holder, name, value)
    }
}
```

</details>

**Comment by icefoxen** [comment]
Parsing "any string that looks like a Foo" is almost never what you actually want in the end; it sounds like a glorious way to get some very annoying and subtle edge cases.

Yes you would hope that an ISO date string is specific enough to not be a problem but that's still an assumption.  Assumptions in specifications is why we need JSON5 over normal JSON in the first place.

**Comment by davidwkeith** [comment]
A few thoughts:

* Dates are great, but we now have Maps, Sets, URLs, and more.
* Hex literals start with `0x`, so there is precedence for 'special strings' defining types in ECMAScript.
* ECMAScript should have other literal formats, it would be nice to have a standard form to define literals.

I agree with the desire to make JSON5 valid ECMAScript, but that doesn't mean we can't advance EMCAScript to meet JSON5's needs. Ultimately we should move both forward in tandem using something like the following syntax:

```javascript
{
  date: @d 05 October 2011 14:48 UTC, // quotes optional
  map: @m {2:"two"}, // or nested array notation
  object: @o {two, 2}, // or nested array notation
  array: @a [1, 2, 'foo', 'foo'], // brackets optional
  float32array: @f32a [21, 31],  // brackets optional
  float64array: @f64a [21, 31],  // brackets optional
  set: @s [1, 2,'foo'],  // brackets optional
  regex: @r /match/i, // or string, but without flags
  function: @f "(arg1, arg2) {alert('hi'); //Kidding, don't do this.}"
}
```

Ultimately I am proposing the following:
* `@<hint-string>` could be an optional way to disambiguate any literal past what the parser would consider the default for a given notation.
* #91 might work better with a hint (see above).
* The hint could be both a short code (`@f32a`) and long (`@float32array`) for clarity.
* Parse errors for anything that does not match the <`hint-string`> object type.

I chose `@` as it matches the Obj-C literal identifier, there may be better choices given the additional information we would want to convey. I can't think of other language conventions at this time.

**Comment by icefoxen** [comment]
Or you could use type constructors as have been used by languages based off of formal type systems for the past 45 years:

```
{
  date: Date("05 October 2011 14:48 UTC"),
  map: Map({2:"two"}),
  object: Object({two, 2}),
  array: [1, 2, 'foo', 'foo'],
  float32array: F32([21, 31]),
  float64array: F64([21, 31]),
  set: Set([1, 2,'foo']),
  regex: Regex("/match/i"),
  function: Function(arg1, arg2, null)
}
```

Is it pretty?  Eh, not really.  Is it simple, unambiguous, extensible, easy to read, easy to parse, and used widely in other languages, including Elm, Rust, and type constructors for just about everything else?  Yes.  How difficult does one really need to make things?

That said, it's probably not valid JS, so.

**Comment by dcleao** [comment]
Finally... Thanks @davidwkeith (although that syntax...) and @icefoxen!
Besides human friendliness, we definitely need an extensible serialization format... 
The case we all miss the most is surely Date. Afterwards, there's Regex and Function.
This could be feasible and safe, as long as the acceptable function names were white-listable and given to the parser. Maybe, even, these should be given to it, as a map of name -> function, so that we don't depend on global variables.
A `reviver` will never be able to do this, alone, without a separate/implied/fixed schema.

**Comment by icefoxen** [comment]
Serialization of functions seems like a special case that increases the hazards involved immsensely.  At that point it's not a matter of "move this data from point A to point B", it becomes "move this program from point A to point B".  Doing that safely in a way general enough to be useful is not, as yet, an easily solved problem.

I'd rather go for the easy 80%, or, since JSON already did that, the mostly-easy 95%, than the people-have-been-trying-for-20-years-and-it-still-sucks 100%.

**Comment by dcleao** [comment]
When I talked about functions, I was referring to your use of `Function(arg1, arg2, ..., body)`, which I presumed would end up being "revived" with the Function constructor. So yes, this would allow creating functions and any other objects, but note: it is up to you what you would pass to `JSON5.parse(jsonString, env)`, in an environment argument. You also know the source of `jsonString`; if it is trustworthy or not.

To make it super clear what I think your proposal would sum up to:
```js
var jsonString = "{" + 
"  prop1: Function(\"a\", "\b", \"return a + b;\")" + 
"}";

var env = {
  "Function": function() {
     return Function.apply(null, arguments);
  }
};

var result = JSON5.parse(jsonString, env);

assert(typeof result === "function");
assert(result.prop1(1, 2) === 3);
```

This is just as dangerous as the existing `reviver` can be...
The only difference is that there would be a special JSON syntax that would make the feature much more interesting. This syntax would make it much more probable that people would end up using common conventions for serialization of dates, etc. Right now, some use `{"type": "Date", value: "2004-01-01"}`, others use `{"_": "Date", v: "2004-01-01"}`, others use "/Date(...)/", etc.
 
Even if you say that, generally, this is unsafe, there are applications where this is a required risk, like component/dashboard editors, where users do specify functions, and these need to  be serialized and deserialized.

**Comment by jordanbtucker** [comment]
Hey, everyone. I'm going to close this issue because it is incompatible with the [official specification](https://json5.github.io/json5-spec/). If you would like to continue this discussion, please open an issue on the [official specification repository](https://github.com/json5/json5-spec). Please see the new [issues template](https://github.com/json5/json5/blob/master/.github/issue_template.md) for more information. Thanks.

**Comment by jordanbtucker** [comment]
This discussion has been continued on the [official specification repository](https://github.com/json5/json5-spec/issues/4).
