### ISSUE TITLE
add key property support ?

### ISSUE THREAD

**Issue by yuanronghhh** [json5/json5#334]
support format like below ：

```text

{
    button<color: "red">: {
         text<font-size:12>: null
    }
}
```

the color property is optional，this is better than children for ui tree:

```text
{
    button: {
        color: "red",
        children: [
            text: null
        ]
    }
}
```

**Comment by jordanbtucker** [comment]
Thank you for the suggestion, but this discussion is outside the scope of this project, as explained in the [Issue Template](https://github.com/json5/json5/blob/master/.github/issue_template.md) you saw when opening this issue.

This discussion belongs on the [JSON5 specification repository](https://github.com/json5/json5-spec), however it will be rejected because JSON5 only supports ES5 syntax.
