### ISSUE TITLE
Add `comma-dangle` option

### ISSUE THREAD

**Issue by rtritto** [json5/json5#336]
Add a `comma-dangle` boolean option.

## Example
With:
```ts
const data = {
  key1: 'value1'
}
```

### Case 1
Options:
```ts
JSON5.stringify(data, null, 2, { commaDangle: false, quote: '\'' })
```
Output:
```ts
{
  key1: 'value1'
}
```

### Case 2 (Current behavior)
Options:
```ts
JSON5.stringify(data, null, 2, { commaDangle: true, quote: '\'' })
```
Output:
```ts
{
  key1: 'value1',
}
```

**Comment by rtritto** [comment]
@jordanbtucker any update?

**Comment by jordanbtucker** [comment]
Thanks for the suggestion. At this time, there is no plan to add this option to the API. The goal of this library is to provide a reference implementation for the JSON5 format, so we try to keep it simple without deviating too much from the [JavaScript JSON API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON).

**Comment by rtritto** [comment]
@jordanbtucker All the examples in [JavaScript JSON API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON) haven't the comma dongle.
Please keep opened this issue, because anyone can see, work or write on it.
If you have no time, I can create a PR.

**Comment by jordanbtucker** [comment]
Sorry, I think you misunderstood me. Adding this option is currently not a design goal for this library. PRs that add this option will not be merged. If this is a feature you need, then I recommend looking at alternative JSON5 libraries like https://github.com/rlidwka/jju

**Comment by rtritto** [comment]
@jordanbtucker as the examples in [JavaScript JSON API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON), the comma dangle should be enabled by default.

Can you do these changes in the `json5/lib/stringify.js` file?
1. Object
    https://github.com/json5/json5/blob/de344f0619bda1465a6e25c76f1c0c3dda8108d9/lib/stringify.js#L199
    ```diff
    -final = '{\n' + indent + properties + ',\n' + stepback + '}'
    +final = '{\n' + indent + properties + '\n' + stepback + '}'
    ```

2. Array
    https://github.com/json5/json5/blob/de344f0619bda1465a6e25c76f1c0c3dda8108d9/lib/stringify.js#L253
    ```diff
    -final = '[\n' + indent + properties + ',\n' + stepback + ']'
    +final = '[\n' + indent + properties + '\n' + stepback + ']'
    ```

**Comment by jordanbtucker** [comment]
When I said "without deviating too much from the JavaScript JSON API", I meant the calling interface of `parse` and `stringify` and the input provided to those functions. The output is necessarily going to be different from the JSON API because it is producing JSON5, not JSON. The JSON API examples do not include trailing commas because trailing commas are not a supported feature of JSON.

This JSON5 library is opinionated in that trailing commas should be included in JSON5 documents that have line breaks. This makes it easier to sort and move entire lines or chunks without having to worry about fixing any commas.

If avoiding trailing commas is a requirement for you, then I recommend using an alternative JSON5 library or forking this one and making the modifications you need.

**Comment by jordanbtucker** [comment]
Locking as this is a duplicate of #344.
