### ISSUE TITLE
JSON5.stringify() option: `trailingCommas`

### ISSUE THREAD

**Issue by rauschma** [json5/json5#344]
I like trailing commas and `JSON5.parse()` already supports them. It may make sense to support them in `JSON5.stringify()`, too. This could look as follows.

`JSON5.stringify(value, {space: 2})`

```jsonc
{
  "name": [
    "Robin",
    "Doe"
  ],
  "age": 52
}
```

`JSON5.stringify(value, {space: 2, trailingCommas: true})`

```jsonc
{
  "name": [
    "Robin",
    "Doe",
  ],
  "age": 52,
}
```

**Comment by jordanbtucker** [comment]
Thanks for your suggestion. `stringify` already includes trailing commas when you provide it with a `space` option, and it omits trailing commas when you don't, since it's expected that you want a more compact output.

The only reason to add a `trailingCommas` option is if you want trailing commas *without* indentation or when you don't want trailing commas *with* indentation. Neither of those situations seem to be that common.

**Comment by rauschma** [comment]
Oh, that’s embarrassing. Apparently, I just assumed and didn’t actually try it out with the `space` option.

The current approach makes complete sense. Apologies for the noise!

**Comment by rtritto** [comment]
@rauschma I did the fix https://github.com/json5/json5/issues/336#issuecomment-2265068330 in branch https://github.com/rtritto/json5/tree/develop (forked from _json5_ repo).

You can:
- install branch using github protocol (e.g. `yarn add json5@github:rtritto/json5#develop`)
- use patch command (e.g. `yarn patch json5`) and do the fix

Currently I haven't published on _npm_ registry
